[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "musmart"
version = "0.1.0"
description = "A toolkit for symbolic music analysis"
readme = "README.md"
authors = [
    { name = "The AMADS team", email = "email@example.com" }
]
license = { text = "TODO" }  # Update with your actual license
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "partitura",
    "music21"
]

[project.urls]
"Homepage" = "https://github.com/yourusername/musmart"  # Update with your repo URL
