[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "amads"
version = "0.1.0dev0"
description = "A toolkit for symbolic music analysis"
readme = "README.md"
maintainers = [
    { name = "Peter Harrison", email = "pmch2@cam.ac.uk"},
    { name = "Roger Dannenberg"},
    { name = "Mark Gotham"}
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy<1.12.0",
    "partitura",
    "music21",
    "pretty_midi",
    "setuptools",  # required for partitura
    "pytest",
    "sphinx-gallery",
    "tenacity",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "sphinx",
    "sphinx-book-theme",
    "sphinx-autodoc-typehints",
    "myst-parser",
    "pre-commit",
]
test = [
    "pretty_midi",
    "pytest>=7.0.0",
    "pytest-cov",
]
melsim = [
    "pandas",
]
examples = [
    # Temporary fix while we wait for mirdata > 0.3.9 to be released
    "mirdata @ git+https://github.com/mir-dataset-loaders/mirdata.git@82b9710a0cc3e4b27a6522f0ec8a92ea03f23c41",
    "scikit-learn"
]

[project.urls]
"GitHub" = "https://github.com/music-computing/amads"  # Update with your repo URL
"Documentation website" = "https://music-computing.github.io/amads/"

[tool.setuptools.packages.find]
include = ["amads", "amads.*"]
