name: Documentation

env:
  # This is needed for R's install_github scripts
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

on:
  push

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup R dependencies
        uses: ./.github/actions/setup-r

      - name: Install dependencies
        run: |
          pip install -e ".[dev, melsim]"

      - name: Sphinx build
        run: |
          sphinx-build docs _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
